{{- $jobName := printf "%s-%s" .Release.Name "database-migration-job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
    {{ include "service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ $jobName }}
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database-migration-job
    spec:
      containers:
      - name: {{ $jobName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
          - migrate -database $POSTGRES_URL -path /usr/local/lib/{{ .Release.Name }}/migrations up
        env:
          - name: POSTGRES_URL
            value: {{ .Values.POSTGRES_URL }}
      restartPolicy: Never
      imagePullSecrets:
        - name: docker-registry-credentials
