apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grpc-server
  labels:
    {{- include "service.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grpc-server
  template:
    metadata:
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grpc-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 8080
              protocol: TCP
          env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: POSTGRES_URL
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc-server
  labels:
    {{- include "service.labels" . | nindent 4 }}
    app.kubernetes.io/component: grpc-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grpc-server
